### ISSUE TITLE
youtube link in vm

### ISSUE THREAD

**Issue by nplimaye** [SoftwareEngineeringToolDemos/FSE-2012-UMLtoCSP-UOST#5]
The youtube link is vm is mis spelled as "youtu.be"

**Comment by shrenujgandhi** [comment]
The YouTube URL is provided in that format by the video manager.

![image](https://cloud.githubusercontent.com/assets/13962371/10786679/b9deb836-7d28-11e5-9bd3-b163612d1f7e.png)
